# Generated by Django 2.1.2 on 2018-10-31 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_auto_20181031_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='status',
            new_name='ativo',
        ),
    ]
