# Generated by Django 2.1.2 on 2018-11-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_empregado_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='foto',
            field=models.ImageField(upload_to='clientes_fotos'),
        ),
    ]
